repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        name: absolufy-imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade
        args:
          - --py310-plus
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3
        args:
          - --target-version=py310
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        language_version: python3
        additional_dependencies:
          # NOTE: autoupdate does not pick up flake8-bugbear since it is a transitive
          #  dependency. Make sure to update flake8-bugbear manually on a regular basis.
          - flake8-bugbear==24.8.19
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      -   id: codespell
          types_or: [rst, markdown]
          files: docs
          additional_dependencies:
            - tomli
  - repo: https://github.com/pre-commit/mirrors-mypy
    # pinned due to
    # https://github.com/python/typeshed/pull/9771 and
    # https://github.com/python/mypy/issues/15257 for DaskCollection.__dask_scheduler__
    rev: v1.11.2
    hooks:
      - id: mypy
        # Override default --ignore-missing-imports
        # Use pyproject.toml if possible instead of adding command line parameters here
        args: [--warn-unused-configs]
        exclude: dask/dataframe/dask_expr/
        additional_dependencies:
          # Type stubs
          # - pandas-stubs  # TODO
          - types-docutils
          - types-PyYAML
          - types-psutil
          - types-requests
          - types-setuptools
          # Typed libraries
          - numpy
          - pytest
